version: "3"
services:
  geth-bootnode:
    hostname: geth-bootnode
    build:
      context: ./bootnode
      args:
        nodekeyhex: dc90f8f7324f1cc7ba52c4077721c939f98a628ed17e51266d01c9cd0294033a #Needs to be fix, so that the miners know the resulting enode id
    ports: 
      - 30301:30301/udp
    networks:
      chainnet: 
        ipv4_address: 172.25.0.101 # The miners need to know the IP address later on

  geth-dev-miner-1:
    hostname: geth-dev-miner-1
    environment:
      - address=0x8cc5a1a0802db41db826c2fcb72423744338dcb0
    build: 
      context: ./miner
      args:
        privatekey: df504d175ae63abf209bad9dda965310d99559620550e74521a6798a41215f46 # Please don't do something like this in production, okay?
        password: pass
    container_name: geth-miner-1
    ports:
      - 8545:8545
    volumes:
      - eth-data-1:/root/.ethash
    networks:
      chainnet:

  geth-dev-miner-2:
    hostname: geth-dev-miner-2
    environment:
      - address=0x3590aca93338b0721966a8d0c96ebf2c4c87c544
    build: 
      context: ./miner
      args:
        privatekey: bc5b578e0dcb2dbf98dd6e5fe62cb5a28b84a55e15fc112d4ca88e1f62bd7c35
        password: word
    container_name: geth-miner-2
    ports:
      - 8546:8545
    volumes:
     - eth-data-2:/root/.ethash
    networks:
      chainnet:

networks:
  chainnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24

volumes:
  eth-data-1:
  eth-data-2:
